// Embed the reference tables into index.html between /* DB-DATA-BEGIN */ and /* DB-DATA-END */.
// Idempotent: run it after fetch.sh + parse-orc + derive-motors + curate-airframes, and again
// whenever data/tables/*.json (the verified reference tables) change.
//   node tools/db/embed.mjs
import fs from 'node:fs';
const root = new URL('../../', import.meta.url).pathname;
const read = (p) => JSON.parse(fs.readFileSync(root + p, 'utf8'));
const KIND = { BodyTube: 'T', TubeCoupler: 'C', CenteringRing: 'R' };
const air = read('data/airframes.json');
const mot = read('data/motors.json');
const data = {
  meta: {
    airframes: 'openrocket/openrocket-database (Apache-2.0) — Dave Cook et al.; curated by tools/db/curate-airframes.mjs',
    motors: 'thrustcurve-db 4.0.1 (ISC) — ThrustCurve.org data by John Coker, rebundled by broofa; derived by tools/db/derive-motors.mjs',
  },
  // [kind, vendor, material, id_mm, od_mm, nominal, pn]
  airframes: air.rows.map(r => [KIND[r.kind] || r.kind, r.vendor, r.material, r.id_mm, r.od_mm, r.nominal, r.pns.slice(0, 2).join('; ')]),
  // [mfr, case, d_mm, len_mm, total_g_min, total_g_max, prop_g_max, classes, example]  — current hardware only
  motors: mot.rows.filter(r => r.current > 0).map(r => [r.mfr, r.case, r.d_mm, r.len_mm, r.total_g_min, r.total_g_max, r.prop_g_max, r.classes, r.example]),
};
// Verified reference tables (fasteners, O-rings, NPT, drills, stock, rails, avionics, and the
// motor/airframe supplements) arrive as data/tables/<name>.json in the compile-workflow shape.
const tdir = root + 'data/tables/';
if(fs.existsSync(tdir)) for(const f of fs.readdirSync(tdir).filter(x => x.endsWith('.json')).sort()){
  const t = read('data/tables/' + f);
  const key = f.replace(/\.final\.json$|\.json$/, '').replace(/-/g, '_');
  data[key] = { columns: t.columns || {}, rows: t.rows || [], notes: t.notes || '', license_note: t.license_note || '', supplement: t.supplement || undefined };
  data.meta[key] = t.license_note || '';
}
const lines = ['/* DB-DATA-BEGIN */ /* generated by tools/db/embed.mjs from data/ — do not edit by hand */', 'const FLIGHT_DB_DATA = {'];
for(const [k, v] of Object.entries(data)) lines.push(`  ${JSON.stringify(k)}: ${JSON.stringify(v)},`);
lines.push('};', '/* DB-DATA-END */');
const literal = lines.join('\n');
const html = fs.readFileSync(root + 'index.html', 'utf8');
const a = html.indexOf('/* DB-DATA-BEGIN */'), b = html.indexOf('/* DB-DATA-END */');
if(a < 0 || b < 0 || b < a) throw new Error('DB-DATA markers not found in index.html — add the DB block first');
const out = html.slice(0, a) + literal + html.slice(b + '/* DB-DATA-END */'.length);
fs.writeFileSync(root + 'index.html', out);
const bytes = Buffer.byteLength(literal);
console.log(`embedded: ${data.airframes.length} airframe rows, ${data.motors.length} motor sets, ${Object.keys(data).filter(k => !['meta', 'airframes', 'motors'].includes(k)).join(', ') || 'no verified tables yet'} — ${bytes} bytes`);
