// Embed the reference tables into index.html between /* DB-DATA-BEGIN */ and /* DB-DATA-END */.
// Idempotent: run it after fetch.sh + parse-orc + derive-motors + curate-airframes, and again
// whenever data/tables/*.json (the verified reference tables) change.
//   node tools/db/embed.mjs
import fs from 'node:fs';
const root = new URL('../../', import.meta.url).pathname;
const read = (p) => JSON.parse(fs.readFileSync(root + p, 'utf8'));
const KIND = { BodyTube: 'T', TubeCoupler: 'C', CenteringRing: 'R' };
const air = read('data/airframes.json');
const mot = read('data/motors.json');
const data = {
  meta: {
    airframes: 'openrocket/openrocket-database (Apache-2.0) — Dave Cook et al.; curated by tools/db/curate-airframes.mjs',
    motors: 'thrustcurve-db 4.0.1 (ISC) — ThrustCurve.org data by John Coker, rebundled by broofa; derived by tools/db/derive-motors.mjs',
  },
  // [kind, vendor, material, id_mm, od_mm, nominal, pn]
  airframes: air.rows.map(r => [KIND[r.kind] || r.kind, r.vendor, r.material, r.id_mm, r.od_mm, r.nominal, r.pns.slice(0, 2).join('; ')]),
  // [mfr, case, d_mm, len_mm, total_g_min, total_g_max, prop_g_max, classes, example]  — current hardware only
  motors: mot.rows.filter(r => r.current > 0).map(r => [r.mfr, r.case, r.d_mm, r.len_mm, r.total_g_min, r.total_g_max, r.prop_g_max, r.classes, r.example]),
};
// Verified reference tables (fasteners, O-rings, NPT, drills, stock, rails, avionics, and the
// motor/airframe supplements) arrive as data/tables/<name>.json in the compile-workflow shape.
const tdir = root + 'data/tables/';
if(fs.existsSync(tdir)) for(const f of fs.readdirSync(tdir).filter(x => x.endsWith('.json')).sort()){
  const t = read('data/tables/' + f);
  const key = f.replace(/\.final\.json$|\.json$/, '').replace(/-/g, '_');
  const rows = t.rows || [];
  const common = (field) => { const v = new Set(rows.map(r => r[field])); return v.size === 1 ? [...v][0] : null; };
  // Formulaic tables embed compact (index.html's dbRows() expands them); everything else as written.
  if(key === 'orings_as568' && rows.length && rows.every(r => typeof r.id_in === 'number' && typeof r.cs_in === 'number')){
    const cConf = common('confidence');
    data[key] = { compact: 'orings', columns: { row: '[dash, id_in, cs_in, confidence?] — mm and OD derived' }, confidence: cConf || undefined, source: common('source') || (t.notes || '').slice(0, 200), rows: rows.map(r => cConf ? [r.dash || r.key, r.id_in, r.cs_in] : [r.dash || r.key, r.id_in, r.cs_in, r.confidence]), notes: t.notes || '', license_note: t.license_note || '' };
  } else if(key === 'drills' && rows.length && rows.every(r => typeof r.in === 'number')){
    const cConf = common('confidence');
    data[key] = { compact: 'drills', columns: { row: '[name, kind, in, confidence?] — mm derived' }, confidence: cConf || undefined, source: common('source') || 'ASME B94.11M', rows: rows.map(r => cConf ? [r.name, r.kind, r.in] : [r.name, r.kind, r.in, r.confidence]), notes: t.notes || '', license_note: t.license_note || '' };
  } else {
    // Object tables: a field every row shares verbatim (typically `source`, often `confidence`) is
    // hoisted to the table and re-attached by dbRows() — twelve copies of the same ISO citation
    // list cost more than the numbers they cite.
    const hoist = {};
    for(const field of ['source', 'confidence']){ const v = common(field); if(v != null && rows.length > 2) hoist[field] = v; }
    const slim = Object.keys(hoist).length ? rows.map(r => { const o = { ...r }; for(const k of Object.keys(hoist)) delete o[k]; return o; }) : rows;
    data[key] = { columns: t.columns || {}, shared: Object.keys(hoist).length ? hoist : undefined, rows: slim, notes: t.notes || '', license_note: t.license_note || '', supplement: t.supplement || undefined };
  }
  data.meta[key] = t.license_note || '';
}
const lines = ['/* DB-DATA-BEGIN */ /* generated by tools/db/embed.mjs from data/ — do not edit by hand */', 'const FLIGHT_DB_DATA = {'];
for(const [k, v] of Object.entries(data)) lines.push(`  ${JSON.stringify(k)}: ${JSON.stringify(v)},`);
lines.push('};', '/* DB-DATA-END */');
const literal = lines.join('\n');
const html = fs.readFileSync(root + 'index.html', 'utf8');
const a = html.indexOf('/* DB-DATA-BEGIN */'), b = html.indexOf('/* DB-DATA-END */');
if(a < 0 || b < 0 || b < a) throw new Error('DB-DATA markers not found in index.html — add the DB block first');
const out = html.slice(0, a) + literal + html.slice(b + '/* DB-DATA-END */'.length);
fs.writeFileSync(root + 'index.html', out);
const bytes = Buffer.byteLength(literal);
console.log(`embedded: ${data.airframes.length} airframe rows, ${data.motors.length} motor sets, ${Object.keys(data).filter(k => !['meta', 'airframes', 'motors'].includes(k)).join(', ') || 'no verified tables yet'} — ${bytes} bytes`);
